% Plot Lyrics to All Star
% Read lyrics
lyrics = readtable("lyrics.txt","TextType","string",...
    "ReadVariableNames",false);

%% 
% If you have Text Analytics Toolbox, wordcloud does preprocessing
w = wordcloud(lower(lyrics.Var1));
title("Lyrics to All Star by Smash Mouth")
saveas(w,"allstar.jpg")
%%
% Otherwise, DIY
words = cellfun(@(x) split(x," "),lyrics.Var1,"UniformOutput",false);
allwords = string(vertcat(words{:}));
allwords = lower(allwords);
wordcloud(allwords);

% Visualize without Stopwords
% w/ Text Analytics Toolbox  erase(lyrics.Var1,stopWords);
%
stops = ["i", "me", "my", "myself", "we", "our", ...
    "ours", "ourselves", "you", "your", "yours", "yourself", ...
    "yourselves", "he", "him", "his", "himself", "she", "her", "hers", ...
    "herself", "it", "its", "itself", "they", "them", "their", "theirs", ...
    "themselves", "what", "which", "who", "whom", "this", "that", "these",...
    "those", "am", "is", "are", "was", "were", "be", "been", "being", "have",...
    "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", ...
    "and", "but", "if", "or", "because", "as", "until", "while", "of", "at",...
    "by", "for", "with", "about", "against", "between", "into", "through", ...
    "during", "before", "after", "above", "below", "to", "from", "up", "down", ...
    "in", "out", "on", "off", "over", "under", "again", "further", "then", ...
    "once", "here", "there", "when", "where", "why", "how", "all", "any",...
    "both", "each", "few", "more", "most", "other", "some", "such", "no", ...
    "nor", "not", "only", "own", "same", "so", "than", "too", "very", ...
    "s", "t", "can", "will", "just", "don", "should", "now"];

wordsnostops = allwords(~ismember(allwords,stops));
wordcloud(wordsnostops);


